import ArrowDownIcon from "@/app/icons/ArrowDownIcon";
import UserWarningIcon from "@/app/icons/UserWarningIcon";
import ShieldWarningIcon from "@/app/icons/ShieldWarningIcon";
import ShieldApproveIcon from "@/app/icons/ShieldApproveIcon";
import CoinsStackIcon from "@/app/icons/CoinsStackIcon";
import GiftIcon from "@/app/icons/GiftIcon";
import React from "react";

export const overviewSection = {
  title: "Overview",
  leftCards: [
    {
      title: "Technical Explanation",
      content:
        "All the yield generated by savUSD is directed to VT-savUSD. In exchange, VT-savUSD pays a pre-determined fee to YT-savUSD to ensure it earns a fixed yield.",
    },
    {
      title: "Market Expectations of Users",
      content:
        "Users who want to earn predictable and competitive yield exposure on top of $savUSD instead of speculative and volatile yield returns can prefer this market.",
    },
    {
      title: "The Source of Fixed Yield",
      content:
        "savUSD generated stablecoin yield through onchain delta-neutral strategies run by Avant.",
    },
  ],
  rightCards: [
    {
      title: "Risks",
      items: [
        {
          icon: <ArrowDownIcon />,
          title: "savUSD Depeg:",
          description:
            "In case of savUSD depeg, users may incur losses on Stable Jack.",
        },
        {
          icon: <UserWarningIcon />,
          title: "Counterparty Risk:",
          description:
            "Risks include duration risk and smart contract risk of Avant.",
        },
        {
          icon: <ShieldWarningIcon />,
          title: "Smart Contracts Risk:",
          description:
            "Like every DeFi protocol, Stable Jack is built on top of smart contracts, so there is always risks associated with them.",
        },
      ],
    },
    {
      title: "Additional info",
      items: [
        {
          icon: <ShieldApproveIcon />,
          title: "Principal Protection:",
          description:
            "Users won't lose their principal for yield exposure, so the asset is fully principal-protected.",
        },
        {
          icon: <CoinsStackIcon />,
          title: "Mint/Redeem Fees:",
          description:
            "There is no mint fee and there is only 0.1% redeem fee.",
        },
        {
          icon: <GiftIcon />,
          title: "Incentives:",
          description: "Users are eligible for Stable Jack Discount Tickets.",
        },
      ],
    },
  ],
};
export const marketCards = [
  {
    title: "Yield Trade Market:",
    content:
      "The yield generated by savUSD is traded between YT-savUSD and VT-savUSD holders",
    width: "w-[375px]",
  },
  {
    title: "Yield Trade Market:",
    icon: "https://app.stablejack.xyz/_next/static/media/rsavax_pt.32962c71.svg",
    width: "w-[250px]",
  },
  {
    title: "Correlated Asset:",
    icon: "https://app.stablejack.xyz/_next/static/media/rsavax_pt.32962c71.svg",
    width: "w-[250px]",
  },
];
